### ISSUE TITLE
resize of telnet console (height and wide) could lead to crash

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#1]
i had a crash on double screen on, on openbox as wm, resizing height and wide larger with mouse

**Comment by enricoT** [comment]
using xterm, i cant read tells, yellow on white, could be possible to test the terminal background or to set it black before running papageorge?

**Comment by enricoT** [comment]
during the game it would be nice to type and enter when focus is on board window, this to make faster commands like accept, draw, adjourn, abort or alias like d = draw, m = moretime 30 etc.. etc.. to not being forced to change focus or to remove mouse from useful position to make next move

**Comment by enricoT** [comment]
when there are many observed games open, it would be nice that the window board with focus is set automatically primary so i can type \* or kibitz + message or whisper or # not forced to add board game number \* 100 chat chat chat.... but \* blablabla

**Comment by drestebon** [comment]
I was able to reproduce the crash. It has to do with an open issue in urwid https://github.com/wardi/urwid/issues/96

I wil work on your suggestions during the week. There are a couple wich will be very easy to implement.

Thank you again!
E

**Comment by drestebon** [comment]
The crash issue has been corrected in urwid in https://github.com/wardi/urwid/pull/153#event-414728687 
The rest of the features have been added

**Comment by enricoT** [comment]
set primary game on observed game with focus, it works if mouse is on board, but if i focus, with Alt+Tab the window, then i cant type on chat, then im not sure, the primary board is set properly in this case. 

ciao im really impressed by work and speed :)
