### ISSUE TITLE
about observing

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#10]
When game is over, board is closed automatically, i suggest to close it only if another window is shown, maybe better to choose to close or hide board with a pop up window: close, hide, close all inactiveboard.
when observing the board if observation starts from late join, then you cannot go backward to first move, this cn be solved with command moves that show the list of all moves since the start.

I see there is a window popup on observed board, it would be nice to see also copygame if observed game is active, this is to examine position (copy game number)

it would be nice to see game   [number]: name player... on tite on top of the window

when i focus on 1 board game, if i type unobserve all games are closed, it woud be better to close one and not all, if i focus on console (then all vould be ok) but i dont really know how to work out, i dont like all games closed, but i dont know how to manage it.

I can move ahead when observing, but i cant go back to real game piece moved cant be replaced back, i have to type refresh.

ciao :)

**Comment by drestebon** [comment]
observed games are not closed anymore when finished
copygame is added to the actions popover
game number is on the title now
the command `unobserve` clears your whole observation list, that's just the way it is, but if you close a single window, that single game is cleared out of yout observation list
I added a simple solution to the 'issing moves on a game being observed' issue. check it out!

**Comment by enricoT** [comment]
:+1:
