### ISSUE TITLE
examine mode - unreproducible crash

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#11]
when i move pieces in examine mode, the piece animated is not cleaned from squarefrom until i complete the move. This happens in first move only. happened only the first examine board maybe is not something i can repeat i dont remember exactly what i have done to reproduceit.

**Comment by drestebon** [comment]
have you been able to reproduce this?

**Comment by enricoT** [comment]
No, i find gold, but  i forget where. :)

**Comment by drestebon** [comment]
I am going to close this for the time being. open it again if you experience further problems
