### ISSUE TITLE
about playng - more actions for popover

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#12]
opponent clock is not well when not his move if you backlight -10 until is close to black screen you can barely see the clock
when game is over if  iclick on board ishould see anther window popup, no more action games, but t close, rematch examine ? and say good game? and set automatic rematch? i dont know how many choice i could, also noplay him :-)

**Comment by drestebon** [comment]
You can change all colors on the configuration. I'll add rematch, examine and saying good game. I believe an auto-rematch and adding people to noplay list could get in the way (if you don't know what you are doing, for example).

**Comment by drestebon** [comment]
done in 49e80d57e5ccba055583a84c092b320d2005c43a and 34f069b790a58c425be815282874d8d92a2e15a1
