### ISSUE TITLE
about console font resize

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#14]
Hi, if i run papageorge with xterm, font is very small, is there a way to resize it when already running? some like ctrl + forward backward, other wise, i have 2 screen, and i would like to have font size fit the screen size is that possible?

HDMI1 --mode 1920x1080 
LVDS1 --mode 1366x768

Or, is there a way to resize font from .config file?

ciao e grazie!

**Comment by drestebon** [comment]
Hello enrico,

There is no way to change the console font in Papageorge. The design is that it runs on a terminal emulator of your choice and changing the font is feature of the terminal emulator.

For changing the font in xterm refer to:

https://wiki.archlinux.org/index.php/Xterm#Fonts
