### ISSUE TITLE
easy start for papageorge with file .icsrc (as in xboard)

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#21]
It's possible to run :+1: 
papageorge $(head ~/icsrc)

if the file is composed 

handle
password

I did not test if after login password is possible to add command as in xboard.

**Comment by drestebon** [comment]
I dont know the format of that file, but we could put startup commands in .papageorge.conf

I would not like to put the username and password there though. I prefer to have them encrypted in another place, but it could be done also.

**Comment by enricoT** [comment]
yes, to use pgp file is better, but eboard and xboard just put the login password in a file script normal i wonder if you just can hide password immission from client as in console or put the pgp command inside the line this way:
handle
pgp --quiet -d ......
so it's not necessary to write everytime the line, or just go for .icsrc or write password from console but not login, i wonder if is possible to add some command after password (t 74 ciao, t 85 ciao on different lines)
xboard format is:
handle
login
command after login
command
command
command

is a script pro and post login without encrypted password

ciao e grazie :)
