### ISSUE TITLE
Name / rating / clock

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#22]
I suggest to make it more readable with justification on the right
______________________Opponent(2000) 29 05:33
a8------------------------------------------------------------- h8
a7
a6
a5
a4
a3
a2
a1
a1-------------------------------------------------------------h1
________________________Handle(1070) 30 03:01

I suggest to remove move number this number move could
be useful in observe or in examine but playng is just some distraction

In case of double screen if im waiting the move and go in other screen
the intelligent menu bar unhide and cover the time running clock, it would
be nice to set game (not other not observe not examine not copygame)
always on top. during the game

**Comment by drestebon** [comment]
The number you refer to is the material. I like to have it because on fast games i get lost. Ill try to think of a way to make this customizable.

I don't know what you mean with 'intelligent menu bar' you mean the actions menu? And what is set game?

**Comment by enricoT** [comment]
my fault, i set menu panel intelligent hide (on bottom of the screen i get the bar menu, applet running, hour, exit button xp style if im not using it,   hide and maximize size (board and client) can invade and cover the panel menu bar) when im playing if i turn the mouse/focus on different screen , the bar popup and covers gameboard section on bottom where clock (my clock) is running. 
For material number i suggest a different way, instead of the absolute sum (wich is necessary to read 2 infos, just give +or- material , so i can read just 1 info.
P=1, N=B=3, R=5, Q=8 so material = me-opponent=0? then  igot equale material, this way is just 1 info that need less time to use and gives immediate perception of material balance.
At the beginning i suggest == symbol then +1 -1 (when up down pawn) myMaterial-OpponentMaterial

**Comment by drestebon** [comment]
You can especify in the configuration if you want to justify the handles right or left ;)
