### ISSUE TITLE
How to run papageorge from icon 

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#25]
from xfce4-terminal is possible to exec the command:
xfce4-terminal -H -e "papageorge" and papageorge ask for login/password this way is possible to run papageorge from desktop file or from launcher, while the next works only from terminal window
xfce4-terminal -H -e "papageorge $(head .icsrc)"
the script is ignored on the launcher, and ask again login & password.

**Comment by drestebon** [comment]
I believe you should use -x instead of -e and without the double quotes

**Comment by enricoT** [comment]
:100:

**Comment by enricoT** [comment]
this is papageorge.desktop
[Desktop Entry]
Type=Application
Version=1.0
Name=papageorge
GenericName=Chess Fics Client
Icon=papageorge.png
Exec=xfce4-terminal -H -x papageorge $(head ./icsrc)
Categories=Game;BoardGame;

it worked before upgrade with latest AUR repo, note that
./icsrc is in the home, and is icsrc not .icsrc i can run it from 
cd and terminal
even with: 
Exec=xfce4-terminal -H -x papageorge $(head /home/enrico/icsrc)
not working

**Comment by drestebon** [comment]
I think this doesnt work because the substitution is  a bash feature. I
could run papa from a laucher in xfce if i put the whole command
xfce4-terminal -H -x papageorge $(head ~/icsrc)
In a script in ~/bin and create a launcher for that. Tell me how it goes ;)
