### ISSUE TITLE
how to customize color console a tells you: Kibitz or whisper or (74) or (255) 

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#27]
I tested this change is rude i think you would write it better aniway define in config.py
# customized colors

yellow = '#ff8'
green = '#0f6'
blue = '#0ff'
red = '#f00'
magenta = '#f0f'
gray = '#ddd'
darkyellow = '#860'
darkgreen = '#0a0'
darkblue = '#08f'
darkred = '#800'
darkmagenta = '#a08'
darkgray = '#88a'

in papageorge.conf add this comment :
; Colors for user yellow green blue red magenta gray or darkyellow to darkgray 

console_highlight = ("^\s+**ANNOUNCEMENT**",         darkyellow)
console_highlight = ("^--> \w+((\w+))_",               yellow)
console_highlight = ("^\w+(([\w\_]+))\* tells you: ",   green)
console_highlight = ("^\w+(([\w*]+))\* (c-)_shouts: ", magenta)
console_highlight = ("^\w+(([\w\_]+))_[(?P<id>\d+)] kibitzes: ", "palette")
console_highlight = ("^\w+(([\w\_]+))_[(?P<id>\d+)] whispers: ", "palette")
console_highlight = ("^\w+(([\w\_]+))_(\d+): ",      "#4dd")
console_highlight = ("^\w+(([\w\_]+))_(50): ",       darkred)
console_highlight = ("^\w+(([\w\_]+))_(53): ",       darkmagenta)
console_highlight = ("^\w+(([\w\_]+))_(74): ",       darkred)
console_highlight = ("^\w+(([\w\_]+))_(85): ",       darkmagenta)
console_highlight = ("^\w+(([\w\_]+))_(1): ",        gray)
console_highlight = ("^\w+(([\w\_]+))*(2): ",        darkgray)

(it's an example to test is working)
I'd like to add estebon tells you: to make a special list of friend but i dont know how to do it

The best would be to add simply ("string", color) without the regex wich is easy to destroy for a newbie (i had experience) 

![](http://urwid.org/_images/palette_test2.png)

```
          #00f#06f#08f#0af#0df#0ff        black_______    dark_gray___
        #60f#00d#06d#08d#0ad#0dd#0fd        light_gray__    white_______
      #80f#60d#00a#06a#08a#0aa#0da#0fa
    #a0f#80d#60a#008#068#088#0a8#0d8#0f8
  #d0f#a0d#80d#608#006#066#086#0a6#0d6#0f6
#f0f#d0d#a0a#808#606#000#060#080#0a0#0d0#0f0#0f6#0f8#0fa#0fd#0ff
  #f0d#d0a#a08#806#600#660#680#6a0#6d0#6f0#6f6#6f8#6fa#6fd#6ff#0df
    #f0a#d08#a06#800#860#880#8a0#8d0#8f0#8f6#8f8#8fa#8fd#8ff#6df#0af
      #f08#d06#a00#a60#a80#aa0#ad0#af0#af6#af8#afa#afd#aff#8df#6af#08f
        #f06#d00#d60#d80#da0#dd0#df0#df6#df8#dfa#dfd#dff#adf#8af#68f#06f
          #f00#f60#f80#fa0#fd0#ff0#ff6#ff8#ffa#ffd#fff#ddf#aaf#88f#66f#00f
                                #fd0#fd6#fd8#fda#fdd#fdf#daf#a8f#86f#60f
  #66d#68d#6ad#6dd                #fa0#fa6#fa8#faa#fad#faf#d8f#a6f#80f
#86d#66a#68a#6aa#6da                #f80#f86#f88#f8a#f8d#f8f#d6f#a0f
```

  #a6d#86a#668#688#6a8#6d8                #f60#f66#f68#f6a#f6d#f6f#d0f
# d6d#a6a#868#666#686#6a6#6d6#6d8#6da#6dd    #f00#f06#f08#f0a#f0d#f0f

  #d6a#a68#866#886#8a6#8d6#8d8#8da#8dd#6ad
    #d68#a66#a86#aa6#ad6#ad8#ada#add#8ad#68d
      #d66#d86#da6#dd6#dd8#dda#ddd#aad#88d#66d        g78_g82_g85_g89_g93_g100
                    #da6#da8#daa#dad#a8d#86d        g52_g58_g62_g66_g70_g74_
      #88a#8aa        #d86#d88#d8a#d8d#a6d        g27_g31_g35_g38_g42_g46_g50_
    #a8a#888#8a8#8aa    #d66#d68#d6a#d6d        g0__g3__g7__g11_g15_g19_g23_
      #a88#aa8#aaa#88a
            #a88#a8a

ciao :)

**Comment by drestebon** [comment]
In 49e80d57e5ccba055583a84c092b320d2005c43a I gave names to the highlights. I also added two special ones:
`channel n` to customize channel `n`
`user x` to customize tells from user `x`

You can also baptize colors
