### ISSUE TITLE
disconnection unwanted makes some trouble

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#28]
Im on notebook disconnected, i was playing and now board game window is locked i cant close it the uh? window popup (btw i suggest descriptive title so i can reportit well uh, already my grammaire is problematic to understand :)
so now i have an immortal window and no easy wayout, btw also the reuse of pg console window after unwanted disconnection is not clear to me what i can do, aniway at the end i closed console and that closed everything.

**Comment by drestebon** [comment]
I added a Close button to the corresponding dialog in 49e80d57e5ccba055583a84c092b320d2005c43a

You can connect again with the special console command `%c`
