### ISSUE TITLE
crash console

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#29]
If  i type moves comman moves 

 then i try t o select moves with shift mouse selection ctrl c (moves layout command selected) if a message comes or a new line from server i lose selection and editor crashes
i dont know if it works but maybe during event selected test should cache console lines or interrupt print new lines till shift is released even cause select is the target and i dont wan t lose it for new line , the aim of user when shift is pressed is to select. maybe :)

**Comment by drestebon** [comment]
Say enrico, after you select you press Ctrl+C?

If that is the case, Ctrl+C kills the python interpreter, which kills papageorge. If what you want to do is copy the selected text, then you don't need to press ctrl+c, its already stored in your primary selection.

**Comment by enricoT** [comment]
I agree, there s no need to ctrl c if selected text
(74): ciao lory
(told 19 players in channel 74 "Italian")
lorychess(74): CIAO
lorychess(74): pedro
pedropablo(74): ohila

> alias e xtell estebon $@
> Alias e replaced.
> This is pasted without ctrl c from selected disappeared text so there is not a problem if you have 3dbutton emulation or 3button real

**Comment by drestebon** [comment]
I had very little use for differentiated PRIMARY and CLIPBOARD selections, so I use a tool called autocutsel to keep them in sync.
