### ISSUE TITLE
observing game, clock is held until i click on board

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#3]
Hi seems that clock is printed on board game only when move is done and not counting waiting for answer move, clock should run always also when focus is in other board  i suppose, or i dont understand how this clock works.

ciao!

**Comment by drestebon** [comment]
Say. Do the name and clock of the player who is playing get a box around
them?

**Comment by enricoT** [comment]
I dont understand the question but for the moment i cant reproduce the problem, maybe is gone with other fix? 
I would considere this issue closed :+1: 

ciao e grazie :)
