### ISSUE TITLE
todo priority suggest

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#35]
Premove and timeseal
save pgn file (observed and played)

Premove and timeseal are necessary because of blitz and lightning games wich are 99% of games

premove is half active at the moment is possible to select piece to move before opponent move, it's about allowing piece in square to also

timeseal i tried for fun timeseal IP_NUMber | papageorge :smile: same console double output (guest and  account registered in same output) in case of multiple accounts could be useful :smile_cat:

**Comment by drestebon** [comment]
premove is already there

I haven't been able to run timeseal in my setup. It says:

timeseal.Linux-i386: dynamic-link.h:57: elf_get_dynamic_info: Assertion `! "bad dynamic tag"' failed.

**Comment by enricoT** [comment]
i usually use timeseal from scidvspc binary, you can find it for linux/mac and windows i rename it timeseal because real name is sort of timeseal.Linux, did you test timeseal from aur or arch repo?
