### ISSUE TITLE
In case of multiple window observed - tab completion

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#40]
It would be nice to Have Game Number *: in title the \* means primary game or another symbol that makes clear wich is the primary game
It could be an excellent feature if i write as first character \* or # (whisper alias) to have a arrow down set to a feature add the game number, where if i press arrow down it shift the game number making shift \* also in board title, but this is maybe to greedy user wish :smiling_imp:

**Comment by drestebon** [comment]
the help files say kibitz and whisper don't take a game number as argument, but send the message to your own game (if your are playing one) or to your primary game (if you are observing).

**Comment by enricoT** [comment]
youre right, my fault the command that allows kibiz directed to a board is xkibitz it would be nice to know wich is primary and in case of console kibitz \* + arrow could direct xkibitz number automatically? sorry for non correct command request could be \* + tab to set automatically xkibitz 234 or xkibitz 45 or back to \* in case of 3 games observed? Aniway this seems to be a really low priority todo :hushed:

**Comment by drestebon** [comment]
This sounds great! what about these proposed completions:

`> tell [channel/handle]`
TAB would cycle through the list of channels you are subscribed to, the handle of the users you have talked to, and who have talked to you

`> * <TAB> -> xkibitz [game_number]`
`> # <TAB> -> xwhisper [game_number]`
    game_number would cycle through the games being observed

We could also have a little more intelligence in our going back through the commands history, for intance, if you type

`> match <UP>`

you would get the last match command you issued.

What else?

**Comment by enricoT** [comment]
i agree, with xtell completion instead of tell, so . is set to talk to latest tell, to include channel is good idea, more than history i would fish xtell from history and from received tell the best would be, i receive a tell, then i can with tab instantly replay.
command completion is a fantastic idea, but i dont know how to do it, perhaps i would add a shortcut to menu user, once i recall xtell user2 with tab, it would begreat to associate a f2 or a tab shift to open user2 menu (match observe finger) to be allowed to navigate inside with tab and select  with space & enter or close with esc.
tab shows xtell user2 then you can write a message or press f2 to open user2 action window could be an idea?  This could be also good for xkibitz or xwhisper ?  maybe shift tab?

**Comment by drestebon** [comment]
The support I just added completes only commands and handles

**Comment by drestebon** [comment]
I believe the general objectives from this discussion have been achieved
