### ISSUE TITLE
observing: ACCOUNT(ELO)TIME when observing

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#41]
when i watch  on the right the name,elo,time the (elo) is above the seccond number of minutes (time)
example

=                                stoccafisso(2821)3:09
i should see
=                                stoccafisso(2821)  03:09 
im not sure is high priority to fix :smile:

**Comment by drestebon** [comment]
The problem here is the font size, I think it would be great if the size you give in the `.conf` is taken as the maximum size, and if the window size is shrunken and the text overlaps, automatically lower its size.
