### ISSUE TITLE
match finger tell clicking on account name

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#43]
if i click several time it opens N windows, i think it should be max 1 window set on latest account clicked.

ciao :)

**Comment by drestebon** [comment]
lol, that's true! would it not be better if there is only one actions window and only change the handle after a click? I can't see the use of having multiple menus for different users, they all dissapear once you click on the action anyway, no?

**Comment by enricoT** [comment]
yes O.o' did not see tthat :)
