### ISSUE TITLE
board game observed button philosophy

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#44]
If action is not allowed or impossible hide that option. This to not offer the user the chance to make mistakes :)
the click on board open the buttons

```
analysebot
stopanalysebot
copygame
follow stoccafisso
follow lurking
refresh
unobserve
```

analysebot and stopanalysebot could be same button with different function using a flag analysis On/Off making different button function would be better to not give options that are not possible to the users or just a switch that start from analyse without controls.
copygame should be allowed only when game is open, when is over copygame opens another game random (that allocates same number from server) so unless you dont want to examine game from scratch having the list from window and setting the game moves from scratch, to hide that button would be better, otherwise we should recover game from history without pointer on that name if there is a serie of match between player1 player2 (or maybe decoding the time game) but seems to me an ugly work.
unobserve should be hide when game is over  because is impossible action.

**Comment by drestebon** [comment]
Some of this is done. I am reluctant to have a single command for analysisbot, since there is many ways to activate it and deactivate it and we should keep track of all of them to guess which button to show. Moreover, anlysisbot very often gets jammed.
