### ISSUE TITLE
function key multiple command

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#45]
ciao, what do you think about allowing multiple command console using function key example...
console_command = ('f2', '"cc"', '"znotify"'. '"ob /s"')
console_command = ('f3', '"sc"', '"se"', '"history name"')
where commands are alias (to create it from server: alias cc command you want) then server receive alias as a command if it's in the list (type alias to see it)

**Comment by drestebon** [comment]
you mean one key issues all the listed commands, one after the other?
