### ISSUE TITLE
what happens if i drop a piece outside the board

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#48]
seems that piece from square vanish, if move is uncomplete the piece should be restored on square from maintaining selection from on, so it would be the same behaviour clicking on emptysquare to complete the move or just selecting another piece.

P.S. i will stopp to add issue until i get a feedback from you ciao!

**Comment by drestebon** [comment]
Hi enrico,

Sorry for the lack of response. I have been very busy with the job hunt and some traveling. I 'll give an eye on the latest issues on the weekend ;)
