### ISSUE TITLE
observed board resize without clock

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#6]
![resizedboard](https://cloud.githubusercontent.com/assets/5571974/10006682/92555502-60bf-11e5-8add-02408b496d73.png)

**Comment by drestebon** [comment]
Thanks enrico. I actually wanted to see the clock.

**Comment by enricoT** [comment]
![clock](https://cloud.githubusercontent.com/assets/5571974/10034734/87a9359a-6193-11e5-91f7-c44c376dd847.png)

**Comment by enricoT** [comment]
there is also a problem of minimum size, i would like to shrink more the image to have 4 board on notebook 14''

**Comment by drestebon** [comment]
Ok, so everything gets drawn! I can't see why your clock does not get refreshed.

There is no minimum size. All that is done by window manager.

**Comment by drestebon** [comment]
indeed there was a minimum size. I correted it.
