### ISSUE TITLE
move mouse policy for faster client/user performance

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#7]
mouse move click/release policy for faster move:

if (square_Clicked == sideToMove || square_Released == sideToMove)
    square_from = square_Clicked
if (square_Clicked == (empty||~sideToMove) || square_Released == (empty || ~sideToMove))
    move

These 2 condition assume that you move as on real board, from square piece to square to capture or to 
empty square.

These 2 if covers any situation with best time used for client, and best user performance correcting 
squareFrom on the run with a release on new squarefrom, and with 1 click you select the squarefrom or squareto
in case of correction.

This 2 cases works also in case of internal client legal move or enabling premove, in this case
control on legal move internal should be delayed after opponent move, and sideToMove should be mySideToMove.

sideToMove means boolean for in that square there is a piece of color sideToMove or mySideToMove

ciao e buon lavoro!

**Comment by drestebon** [comment]
I I understand this correctly, you would like that, when its white move and white drops a white piece on a white piece, the square_from should be set to the square where just dropped.
If this is so, I just added this. behaviour

**Comment by enricoT** [comment]
nice i usually make mistakes selecting piece square from. Aniway, if i double click on same square, i select deselect piece, this is not an action due, if i can select from just click to other piece, selecting double same piece is a double affirmation, not  a negation of first action. So i would expect this behavior, double select = select, so:
if (square_Clicked == sideToMove || square_Released == sideToMove)
square_from = square_Clicked
if i double click should be always square_from = square_clicked

by square_clicked i mean piece sideToMove selected as pieceToMove in square_from, this way makes faster the move once user realizes that is impossible to deselect square from once is selected, unless another piece is selected to move.

**Comment by drestebon** [comment]
You are very right, I changed this behaviour.

**Comment by enricoT** [comment]
On examine (i assume same in playing):
If i click on piece and i release the piece on same square by mistake, the piece is unselected, so  i have to reselect in order the play, i suggest this behaviour:
At the beginning move at MyColor (start or opponent moved)

```
onMyColor(clicked | released)) ? squareFrom = true, from=mousesquare;
else
onHisColor((clicked|realesed) & squareFrom) ? move(from,to=mousesquare)
else
onEmpty((clicked|realesed) & squareFrom) ? move(from,to=mousesquare)
```

clicked | released are boolean for event mouse true
| is Or clicked or realesed is clicked = true Or released = true
This way (hope) all possibilities are match, in case of legal move control myColor has not to be pinned, unless squareto capture pinned or stay on same pinned path

In case of premove this could be a mess :) 

P.S i dont see anychanges on project since 5 days, how do i know if you made some change? are updates always visible?

ciao e grazie!

**Comment by drestebon** [comment]
this is fixed

**Comment by enricoT** [comment]
:1 perfect!
