### ISSUE TITLE
tiling 2 board vertically

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#9]
using pytyle if i tyle windows this is result correct size vertical is the chromium window, papageorge layout trespass the screen 1 to screen 2
![tiling](https://cloud.githubusercontent.com/assets/5571974/10039613/2abf3d16-61d4-11e5-9ab4-94b993caa2ce.png)

**Comment by enricoT** [comment]
when are 2 board size is not defined by screen
![sizeboard](https://cloud.githubusercontent.com/assets/5571974/10039661/9a56e91c-61d4-11e5-83ce-39fe2d768b03.png)

**Comment by drestebon** [comment]
I don't really get this. In any case, resizing and placement should be managed by window manager

**Comment by drestebon** [comment]
indeed there was a minimum size. Fixed it!

**Comment by enricoT** [comment]
yes now it's perfect!
